Business-objectives
DgtlBureau/zarubin_site pull request #47
Opened 2024-06-13 13:22 UTC by uzarsalan

2024-06-13 18:15 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/e0b0ab34-675c-4d4e-9a3a-09587df8e81c)

Потерялся opacity

2024-06-13 18:15 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/6dc4c3ac-3725-4781-818b-5f4b9e008770)

Ненужные border-radius

2024-06-13 18:19 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/686c8c76-63d3-4a51-a19b-09be263a5871)

на мобилке слишком большой шрифт в футере

2024-06-13 18:24 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/bdf7e681-0f07-4964-8c4b-a546ae4b73eb)

Тут надо уточнить, на декстопе нет бэкграунда заголовка, на таблете и мобилке есть

2024-06-13 18:25 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/44297c6a-4752-477a-838a-6316cb01ec2d)

На мобилке вместо пачки тегов появляется горизонтальный скролл

2024-06-13 18:27 UTC, vladilen597 requested changes
Поправить комменты

2024-06-13 18:27 UTC, vladilen597 commented on app/globals.css
> +  /* border: 0; */
Убрать коммент

2024-06-13 18:40 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/31d3ef0e-b7a0-4967-be66-1f063db8c5d8)

Большой отступ сверху + бэкграунд с тенью снизу

2024-06-13 18:40 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/d5b1c77a-c9bb-4f46-a5e9-e1e1d596b708)

Разный текст

2024-06-13 18:48 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/b0d783e1-7f3a-4a94-acfc-54110685b766)

Тут из-за скролла со sticky на моем экране остается не видно карточек внизу (вопрос скорее к дизайну, но можешь попробовать как-то пофиксить под динамический height vh)

2024-06-13 18:49 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/2c0353b7-6bd4-4879-9b9f-5064ce29c894)

Line-height у текста слишком большой

2024-06-13 18:52 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/6ba1f8af-9005-467b-8a6a-98e6b11104b9)

Здесь поменяй overflow-x на авто, потому что скролл есть даже когда всё влезает в ширину.
Если есть возможность, лучше бы застайлить хоть как-то под стиль сайта этот скролл

2024-06-13 18:53 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/8f646fe0-6a1a-4c4d-9bdb-1a1d5efa59a9)

Тут тоже радиус только внизу у бордеров

2024-06-14 08:12 UTC, vladilen597 commented
![image](https://github.com/DgtlBureau/zarubin_site/assets/45649644/93f8ca6e-d84a-4c32-b12b-f6e5133b660b)

Потерялся квадрат черный между блоками

2024-06-14 10:45 UTC, uzarsalan commented
> ![image](https://private-user-images.githubusercontent.com/45649644/339691483-93f8ca6e-d84a-4c32-b12b-f6e5133b660b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjE5OTYsIm5iZiI6MTcxODM2MTY5NiwicGF0aCI6Ii80NTY0OTY0NC8zMzk2OTE0ODMtOTNmOGNhNmUtZDg0YS00YzMyLWIxMmItZjZlNTEzM2I2NjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEwNDEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMDdhYTI0MmNmNjJiYWM1MDI3ZTQ3Y2RjYTZhMjAyNTY1ZDhlZDE4OWU1YTc1MGE5Nzg3ZjBiNGU2NjVkMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bnpvw2_PpyzjE0gHGypl9fhKxEgRzET0Ym169MdhWqo)
> 
> Потерялся квадрат черный между блоками
> 
> В /expertise
> 
> ![image](https://private-user-images.githubusercontent.com/45649644/339691981-a763dd80-8c9e-43c6-b208-dec12a7a384a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjE5OTYsIm5iZiI6MTcxODM2MTY5NiwicGF0aCI6Ii80NTY0OTY0NC8zMzk2OTE5ODEtYTc2M2RkODAtOGM5ZS00M2M2LWIyMDgtZGVjMTJhN2EzODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDEwNDEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOGE2MWUyZmY0NmI4ZTljZDYzM2QyM2E0MjQ4MTE0MTMxNjRkOTc4MDU1NjljZmVkOTA2MGYwYTM3OGZhMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wfWvShYC_q86k7YsdJjQjfgVykQKqf-JT5hN4_bOqok) Лишний отступ между хедером и оглавлением

На разных страницах по разному в дизайне. Я просто выбрал один, наиболее приемлемый на мой взгляд вариант. Пока делаю merge, если что поправим

2024-06-14 10:45 UTC, merged